apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/hwan/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sat, 18 Sep 2021 18:48:18 KST
        provider: minikube.sigs.k8s.io
        version: v1.22.0
      name: cluster_info
    server: https://127.0.0.1:56816
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sat, 18 Sep 2021 18:48:18 KST
        provider: minikube.sigs.k8s.io
        version: v1.22.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube-default
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sat, 18 Sep 2021 18:48:18 KST
        provider: minikube.sigs.k8s.io
        version: v1.22.0
      name: context_info
    namespace: develop
    user: my-admin
  name: minikube-develop
current-context: minikube-develop
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/hwan/.minikube/profiles/minikube/client.crt
    client-key: /Users/hwan/.minikube/profiles/minikube/client.key