apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-vol-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: soma-nginx
  template:
    metadata:
      labels:
        app: soma-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports: 
        - containerPort: 80
        volumeMounts:
        - mountPath: /user/share/nginx/html
          name: my-volume
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: pvc-hostpath