apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soma
  template:
    metadata:
      labels:
        app: soma
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: SOMA_VERSION_VALUE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-database
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-database
              key: password
