apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-nginx
spec:
  selector:
    matchLabels:
      app: soma
  template:
    metadata:
      labels:
        app: soma
    spec:
      containers:
      - name: my-nginx
        image: docker.io/image/lovehyun/lovehyun-private
        ports: 
        - containerPort: 80
      imagePullSecrets:
      - name: dockersecret

